/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    'border-neon-green',
    'border-neon-yellow',
    'border-neon-orange',
    'border-neon-blue',
    'text-neon-green',
    'text-neon-yellow',
    'text-neon-orange',
    'text-neon-blue',
    'bg-neon-green',
    'bg-neon-yellow',
    'bg-neon-orange',
    'bg-neon-blue',
    'shadow-neon-green',
    'shadow-neon-yellow',
    'shadow-neon-orange',
    'shadow-neon-blue',
    'from-neon-green',
    'from-neon-yellow',
    'from-neon-orange',
    'from-neon-blue',
    'to-neon-green',
    'to-neon-yellow',
    'to-neon-orange',
    'to-neon-blue',
    'border-neon-green/30',
    'border-neon-yellow/30',
    'border-neon-orange/30',
    'border-neon-blue/30',
    'bg-gradient-to-r',
    'from-neon-green',
    'to-neon-blue',
    'animate-pulse-slow',
    'animate-glow',
    'animate-float',
    'animate-gradient',
  ],
  theme: {
    extend: {
      colors: {
        'cyber-dark': '#0b0f1c',
        'neon-green': '#00ff9d',
        'neon-yellow': '#ffd700',
        'neon-orange': '#ff6a00',
        'neon-blue': '#00eaff',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'float': 'float 6s ease-in-out infinite',
        'gradient': 'gradient 3s ease infinite',
      },
      keyframes: {
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(0, 255, 157, 0.5), 0 0 10px rgba(0, 255, 157, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(0, 255, 157, 0.8), 0 0 30px rgba(0, 255, 157, 0.5)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
    },
  },
  plugins: [],
}
